version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: generic-nodejs
    depends_on:
      - db
    deploy:
      replicas: 1
    #restart: unless-stopped
    env_file: .env
    environment:
    #  - MONGO_USERNAME=$MONGO_USERNAME
    #  - MONGO_PASSWORD=$MONGO_PASSWORD
    #  - MONGO_HOSTNAME=db
    #  - MONGO_PORT=$MONGO_PORT
    #  - MONGO_DB=$MONGO_DB

      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

    #  - NODE_ENV=$NODE_ENV
    #  - NODE_DEBUG=$NODE_ENV
    #  - DEBUG=$DEBUG
      - JWT_SECRET=$JWT_SECRET
      - PORT=80
    ports:
      - "80:80"
      - "9992:9229"
    volumes:
      - .:/home/node/app
      - generic-node_modules:/home/node/app/node_modules
    networks:
      - app-network
    entrypoint: ./entrypoint.sh
  #mongo_db:
  #  image: bitnami/mongodb:latest
  #  container_name: generic-db
  #  restart: unless-stopped
  #  env_file: .env
  #  environment:
  #    - MONGODB_USERNAME=$MONGO_USERNAME
  #    - MONGODB_PASSWORD=$MONGO_PASSWORD
  #    - MONGODB_DATABASE=$MONGO_DB
  #    - MONGODB_ROOT_PASSWORD=$MONGO_PASSWORD
  #    - MONGODB_DISABLE_SYSTEM_LOG=true
  #  ports:
  #    - 5555:27017
  #  volumes:
  #    - ./db/mongo_data:/data/db
  #  networks:
  #    - app-network
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: generic-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_HOST=%
    ports:
      - "8000:3306"
    volumes:
      - generic_mysql_data:/var/lib/mysql:rw,delegated
      - "./db/entry.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - app-network
    stdin_open: true
    tty: true

    # removes this error -> mbind: Operation not permitted
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
networks:
  app-network:
    driver: bridge

volumes:
  generic-node_modules:
  generic_mysql_data:
  #generic-mongo_dbdata:

